### ISSUE TITLE
Wrong path for cmake in gitmodules

### ISSUE THREAD

**Issue by petrikvladimir** [stack-of-tasks/dynamic_graph_bridge_msgs#15]
It is not possible to recursively clone this repository because of the wrong path (I assume).
This
`git://github.com/jrl-umi3218/jrl-cmakemodules.git`
should change to:
`https://github.com/jrl-umi3218/jrl-cmakemodules.git`

Thanks,
Vladimir

**Comment by nim65s** [comment]
This was fixed in https://github.com/stack-of-tasks/dynamic_graph_bridge_msgs/pull/10, but no release was made. I'll do this asap, sorry for the delay

**Comment by nim65s** [comment]
Done, thanks for the report :)
